# Generated by Django 5.0.3 on 2024-03-12 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('department', models.CharField(default='Trainee', max_length=50)),
                ('mobile_number', models.IntegerField(null=True)),
                ('gender', models.CharField(default=None, max_length=10)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('country', models.CharField(default='India', max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('pincode', models.IntegerField(default=None)),
                ('file', models.FileField(null=True, upload_to='uploads')),
            ],
        ),
    ]
