# Generated by Django 5.0.3 on 2024-03-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0005_alter_emp_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
