# Generated by Django 5.0.3 on 2024-03-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0006_alter_emp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='reason',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
