# Generated by Django 5.0.3 on 2024-03-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0008_alter_emp_emp_code_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
